### ISSUE TITLE
Need to provide Idb property (getter), but unable to submit pull request

### ISSUE THREAD

**Issue by peter-villadsen** [andrzejolszak/sharpalog#1]
I am writing a tool that allows your engine to be used interactively in a nice environment. It allows you to see all the facts and rules and allows you to execute and see results. It is something that I needed for some experiments, and I ended up being quite pleased with it (please see the enclosed screenshot). However, to provide the program view, I needed to be able to traverse the Idb, and this was a private member. I added a public property with a getter to access it, and it works fine.

Even though the change is trivial I wanted to submit this change as a pull request, but you have not opened up for contributions from 3rd parties. You might want to reconsider that, since you might benefit from the contributions of others.

Also, if anyone wants to use your code, they will have to include it in their project. I do not really want to check in your excellent code in my own github repo, so I was wondering if you would consider making it available in a nuget package? This is how software is typically consumed today and it makes life easy for everyone. I would be happy to help, but I cannot, since you do not accept pull requests.

Best Regards
Peter Villadsen

![Datalog Explorer](https://user-images.githubusercontent.com/79116119/146246897-3f3b0c46-f35e-4320-a56e-6cf9462c6198.png)

**Comment by andrzejolszak** [comment]
Hi Peter,

Thanks for letting me know about your tool, it looks great, and would gladly try it out!
I was actually thinking to prepare something similar in the future based on Blazor https://github.com/andrzejolszak/picat-blazor-monaco-ide , but that would happen after I go outside of pure datalog with the syntax, and I'm not yet sure when this will happen of how it will look like exactly. This is just to say: if one day you want to play around with porting your tool to web with Blazor, that project should be a good starting point ;-)

As far as I can see pull requests should be possible - but I don't see your fork of the repo. Are you sure you have forked the repo and trying to make a pull request, or maybe you have just checked it out and trying to push?

While I will probably not open up for direct pushing, I will gladly accept pull requests. Please feel free to propose any changes that are reasonably self-contained (i.e. big refactorings might be a no), and I will try to make it work.

Btw. I was generally not planning to think about backwards compatibility in this project, but knowing you're using it, just let me know whenever I happen to break you and I will try to fix.

Please feel free to let me know if you need help, or have questions.

BR,
Andrzej

**Comment by peter-villadsen** [comment]
I could absolutely have made the mistake you mention so I restarted the effort. I used the git command line instead of the excellent UI in VS 2022 to make things easy to document.

Here is what I did:

C:\Users\peter>git clone https://github.com/andrzejolszak/sharpalog.git
Cloning into 'sharpalog'...
remote: Enumerating objects: 422, done.
remote: Counting objects: 100% (422/422), done.
remote: Compressing objects: 100% (267/267), done.
Receiving objects:  9remote: Total 422 (delta 277), reused 276 (delta 131), pack-reused 0
Receiving objects: 100% (422/422), 2.09 MiB | 3.46 MiB/s, done.
Resolving deltas: 100% (277/277), done.

C:\Users\peter>cd sharpalog

C:\Users\peter\sharpalog>git checkout -b pvillads/addinggetter
Switched to a new branch 'pvillads/addinggetter'

C:\Users\peter\sharpalog>git branch
  master
* pvillads/addinggetter

Made changes to the universe file. The other changes are caused by VS changing the net version to 4.8. Only staging the universe.cs below.

C:\Users\peter\sharpalog>git status
On branch pvillads/addinggetter
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ConsoleApp1/App.config
        modified:   ConsoleApp1/Sharplog.csproj
        modified:   ConsoleApp1/Sharplog/Universe.cs
        modified:   Sharplog.Benchmarks/Sharplog.Benchmarks.csproj
        modified:   Sharplog.Benchmarks/packages.config
        modified:   SharplogTest/SharplogTest.csproj

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Sharplog.Benchmarks/app.config

no changes added to commit (use "git add" and/or "git commit -a")

Check that the changes were made:

C:\Users\peter\sharpalog>git diff ConsoleApp1\Sharplog\Universe.cs
diff --git a/ConsoleApp1/Sharplog/Universe.cs b/ConsoleApp1/Sharplog/Universe.cs
index 7162a9d..7ee39f3 100644
--- a/ConsoleApp1/Sharplog/Universe.cs
+++ b/ConsoleApp1/Sharplog/Universe.cs
@@ -95,6 +95,12 @@ namespace Sharplog
         private EdbProvider edbProvider;

         private Dictionary<string, HashSet<Rule>> idb;
+        public IDictionary<string, HashSet<Rule>> Idb {
+            get
+            {
+                return this.idb;
+            }
+        }

         private Dictionary<string, Rule> idbRuleIds;


Stage and commit:

C:\Users\peter\sharpalog>git add ConsoleApp1\Sharplog\Universe.cs

C:\Users\peter\sharpalog>git status
On branch pvillads/addinggetter
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   ConsoleApp1/Sharplog/Universe.cs
...

C:\Users\peter\sharpalog>git commit -m "Added getter for Idb"
[pvillads/addinggetter 8effcd3] Added getter for Idb
1 file changed, 6 insertions(+)

C:\Users\peter\sharpalog>git push --set-upstream origin pvillads/addinggetter
remote: Permission to andrzejolszak/sharpalog.git denied to peter-villadsen.
fatal: unable to access 'https://github.com/andrzejolszak/sharpalog.git/': The requested URL returned error: 403

Let me know if you need an expression parser.

Also: Have you seen the King of Datalog implementations: Souffle (Soufflé | Soufflé * A Datalog Synthesis Tool for Static Analysis (souffle-lang.github.io)<https://souffle-lang.github.io/>). It is designed for really heavy loads but it does not run on windows. This addresses my main interest, which is analysing source code. Take a look, if you have not already.

BR PV

**Comment by andrzejolszak** [comment]
Hi Peter,

Thanks. Yes, it looks like this is what is happening: you have checked out this repo and made changes to it that you are trying to push.

This is prevented by default by github (can be configured afterward), as they want people to use forking and pull requests.

I could make your change directly to the repo, but it sounds like you want to do it the right way, and if you have more changes in the future then it make sense to have a fork in place:
1. On the github repo page use the "Fork" button in the upper tight corner
2. Check out your fork that you just made
3. Make your changes and push to your fork
4. After that you should see your changes in your fork - then, on github there should be a button somewhere to send a pull request with your changes
5. Having the fork in place you also have the flexibility to fetch upstream changes from my repo to your fork so that you are always up to date. However, if at any point you don't like where the original repo is going you can just choose not to fetch.

I hope this helps!

BR,
Andrzej
